pipeline {
  agent any

  stages('Hello Worl') {
    steps {
      echo "Hello World"
    }
  }
  stage('Build') {
    steps {
      echo "Building"
    }
  }
  stage('Deploy') {
    steps {
      echo "Deploying"
    }
  }
  stage('Test') {
    steps {
      echo "Testing"
    }
  }
  stage('Release') {
    steps {
      echo "Releasing"
    }
  }
}
}
